# Read the saved reference metadata at configure time; no JSON library is needed
# in the runtime or tests, and no reference inference is performed on the host.
set(POLICY_FIXTURE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/tests/fixtures/policy")

function(verify_policy_fixture manifest_name file_key hash_key)
    file(READ "${POLICY_FIXTURE_DIR}/${manifest_name}" manifest)
    string(JSON filename GET "${manifest}" "${file_key}")
    string(JSON expected GET "${manifest}" "${hash_key}")
    file(SHA256 "${POLICY_FIXTURE_DIR}/${filename}" actual)
    if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "Policy fixture checksum mismatch: ${filename}")
    endif()
endfunction()

verify_policy_fixture(manifest.json weights_file weights_sha256)
verify_policy_fixture(golden-vectors.json values_file values_sha256)

file(READ "${POLICY_FIXTURE_DIR}/golden-vectors.json" golden)
string(JSON case_count LENGTH "${golden}" vectors)
string(JSON value_count GET "${golden}" values_count)
math(EXPR last_case "${case_count} - 1")
set(case_header "// Generated from the saved reference metadata.\n#pragma once\n")
string(APPEND case_header "inline constexpr int kGoldenValueCount = ${value_count};\n")
string(APPEND case_header "struct GoldenCase { int turn, candidates, stats, remaining, logits; };\n")
string(APPEND case_header "inline constexpr GoldenCase kGoldenCases[] = {\n")
foreach(index RANGE ${last_case})
    string(JSON turn GET "${golden}" vectors ${index} turn)
    string(APPEND case_header "    {${turn}")
    foreach(field IN ITEMS candidate_mask candidate_stats remaining_action_mask raw_logits)
        string(JSON offset GET "${golden}" vectors ${index} ${field} offset_floats)
        string(APPEND case_header ", ${offset}")
    endforeach()
    string(APPEND case_header "},\n")
endforeach()
string(APPEND case_header "};\n")
file(CONFIGURE OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/golden_cases.hpp" CONTENT "${case_header}" @ONLY)
